### ISSUE TITLE
Report portal integration throwing errors.

### ISSUE THREAD

**Issue by secxena** [carrier-io/dusty#90]
Type of creds used:
1. IP:port 
2. default profile api
3. launch
4. project

Error Trace:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/reportportal_client/service_async.py", line 89, in _monitor
    self.handle(record)
  File "/usr/local/lib/python3.6/dist-packages/reportportal_client/service_async.py", line 70, in handle
    handler(record)
  File "/usr/local/lib/python3.6/dist-packages/reportportal_client/service_async.py", line 233, in process_item
    getattr(self.rp_client, method)(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/reportportal_client/service.py", line 148, in start_launch
    self.launch_id = _get_id(r)
  File "/usr/local/lib/python3.6/dist-packages/reportportal_client/service.py", line 30, in _get_id
    return _get_data(response)["id"]
  File "/usr/local/lib/python3.6/dist-packages/reportportal_client/service.py", line 50, in _get_data
    raise ResponseError(error_messages[0])
reportportal_client.errors.ResponseError: You do not have enough permissions.

**Comment by arozumenko** [comment]
This happened after permission system upgrade in RP. Basically it say that user is not able to retrieve the data from API.
@LifeDJIK could you please take a look. Folks in RP reduced scope of permissions for token authenticated users.

**Comment by secxena** [comment]
I was trying to run this in a Kubernetes cluster instead of saving the data in a persistent volume anyone can you two things quite easily.
1. ReportPanel giving an error
2. STMP - Gmail integration also resulting in error

(534, b'5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbs\n5.7.14 Stn6mNGdZj9HKYhd_Wme4bwdJeLvbAQtMjHSQJrq6wa_NR06tmerLHt6rnYxAvPrWo08u\n5.7.14 36osAtckjA7__qWKBbClCqJB7KgpjJbygRQwpBmktjKexuFeROsjNNoUoSgOKU-y>\n5.7.14 Please log in via your web browser and then try again.\n5.7.14  Learn more at\n5.7.14  https://support.google.com/mail/answer/78754 v55sm7589298qtc.1 - gsmtp')
Traceback (most recent call last):
  File "/usr/local/bin/run", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/dusty/run.py", line 340, in main
    default_config, test_configs = config_from_yaml(args)
  File "/usr/local/lib/python3.6/dist-packages/dusty/run.py", line 225, in config_from_yaml
    email_service, email_attachments = parse_email_config(execution_config)
  File "/usr/local/lib/python3.6/dist-packages/dusty/run.py", line 154, in parse_email_config
    emails_receivers_email_list, emails_subject, emails_body)
  File "/usr/local/lib/python3.6/dist-packages/dusty/drivers/emails.py", line 35, in __init__
    self.server.quit()
  File "/usr/lib/python3.6/smtplib.py", line 984, in quit
    res = self.docmd("quit")
  File "/usr/lib/python3.6/smtplib.py", line 420, in docmd
    self.putcmd(cmd, args)
  File "/usr/lib/python3.6/smtplib.py", line 367, in putcmd
    self.send(str)
  File "/usr/lib/python3.6/smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

Tried login many times in web changed the setting to as insecure as possible to test if it can work but not working.

**Comment by arozumenko** [comment]
@secxena seems like gmail says that you need to pass auth - https://support.google.com/mail/answer/78754

It happens when google thinks that it is unauthorized automated usage attempt.
