### ISSUE TITLE
nmap scan failing with 'argument list too long' when run in gitlab pipeline

### ISSUE THREAD

**Issue by rsilvernagel** [carrier-io/dusty#96]
When running dast tests locally I have no issues, but when running from our gitlab pipeline I'm getting the following error which is likely an OS limitation:

2020.04.17 17:36:06 UTC -    ERROR - dusty.scanners.performer - Scanner Nmap failed
67 Traceback (most recent call last):
68   File "/usr/local/lib/python3.6/dist-packages/dusty/scanners/performer.py", line 125, in perform
69     future.result()
70   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
71     return self.__get_result()
72   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
73     raise self._exception
74   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
75     result = self.fn(*self.args, **self.kwargs)
76   File "/usr/local/lib/python3.6/dist-packages/dusty/scanners/performer.py", line 161, in _execute_scanner
77     scanner.execute()
78   File "/usr/local/lib/python3.6/dist-packages/dusty/scanners/dast/nmap/scanner.py", line 93, in execute
79     ], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
80   File "/usr/lib/python3.6/subprocess.py", line 423, in run
81     with Popen(*popenargs, **kwargs) as process:
82   File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
83     restore_signals, start_new_session)
84   File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
85     raise child_exception_type(errno_num, err_msg, err_filename)
86 OSError: [Errno 7] Argument list too long: 'nmap'

Is there any recommendation on how to modify the nmap configuration to avoid this issue?

Our runner image is based on the latest dast image, getcarrier/dast:latest

**Comment by rsilvernagel** [comment]
Additional info from the runner image:

```
28 $ uname -a
29 Linux runner-d3347dec-project-13323-concurrent-1p682d 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
30 $ ulimit
31 unlimited
```

**Comment by arozumenko** [comment]
@rsilvernagel 
could you please share sample of config you used and docker run command?

I will check and provide suggestions.

**Comment by arozumenko** [comment]
@rsilvernagel 
were you able to overcome the issue?
